theme: jekyll-theme-minimal
name: FMIE2021 
title: Formal Methods for the Informal Engineer
description: ["Online event February 3-5 2021. Hosted by the Broad Institute of MIT and Harvard"]
site.github.is_user_page: false
