theme: jekyll-theme-minimal
name: FMIE2021 
title: Formal Methods for the Informal Engineer
description: ["February 3-5 2021 at the Broad Institute of MIT and Harvard"]
site.github.is_user_page: false
