theme: jekyll-theme-minimal
name: Formal Methods for the Informal Engineer
title: FMIE2021
description: ["February 3-5 2021 at the Broad Institute of MIT and Harvard"]
site.github.is_user_page: false
